import * as vscode from 'vscode';

/**
 * Completion provider for FPB language
 * Provides autocompletion for keywords, operators, and block delimiters
 */
export class FpbCompletionProvider implements vscode.CompletionItemProvider {
    /**
     * Provide completion items for the current position
     */
    provideCompletionItems(
        document: vscode.TextDocument,
        position: vscode.Position,
        token: vscode.CancellationToken,
        context: vscode.CompletionContext
    ): vscode.CompletionItem[] | vscode.CompletionList {
        const linePrefix = document.lineAt(position).text.substring(0, position.character);
        const completions: vscode.CompletionItem[] = [];

        // Check if we're after an identifier (for connection operators)
        const afterIdentifier = /\b[a-zA-Z_]\w*\s+$/.test(linePrefix);

        if (afterIdentifier) {
            // Suggest connection operators after an identifier
            completions.push(...this.getConnectionOperatorCompletions());
        } else {
            // Suggest keywords, block delimiters, and other completions
            completions.push(...this.getKeywordCompletions());
            completions.push(...this.getBlockDelimiterCompletions());
        }

        return completions;
    }

    /**
     * Get completion items for FPB keywords (element types)
     */
    private getKeywordCompletions(): vscode.CompletionItem[] {
        const keywords = [
            {
                label: 'product',
                snippet: 'product ${1:ID} "${2:Label}"',
                description: 'Material or immaterial goods that are created by one or more processes',
                detail: 'Product element'
            },
            {
                label: 'energy',
                snippet: 'energy ${1:ID} "${2:Label}"',
                description: 'Energy flow required for or generated by processes',
                detail: 'Energy element'
            },
            {
                label: 'information',
                snippet: 'information ${1:ID} "${2:Label}"',
                description: 'Information or data used in the process',
                detail: 'Information element'
            },
            {
                label: 'process_operator',
                snippet: 'process_operator ${1:ID} "${2:Label}"',
                description: 'Process that transforms inputs into outputs',
                detail: 'Process Operator element'
            },
            {
                label: 'technical_resource',
                snippet: 'technical_resource ${1:ID} "${2:Label}"',
                description: 'Technical resource or equipment used in the process',
                detail: 'Technical Resource element'
            },
            {
                label: 'title',
                snippet: 'title "${1:Diagram Title}"',
                description: 'Diagram title',
                detail: 'Title keyword'
            },
            {
                label: 'system',
                snippet: 'system "${1:System Name}" {\n  $0\n}',
                description: 'System block to group elements into a subsystem',
                detail: 'System block'
            }
        ];

        return keywords.map(kw => {
            const item = new vscode.CompletionItem(kw.label, vscode.CompletionItemKind.Keyword);
            item.insertText = new vscode.SnippetString(kw.snippet);
            item.documentation = new vscode.MarkdownString(kw.description);
            item.detail = kw.detail;
            item.sortText = `0_${kw.label}`; // Sort keywords first
            return item;
        });
    }

    /**
     * Get completion items for block delimiters
     */
    private getBlockDelimiterCompletions(): vscode.CompletionItem[] {
        const delimiters = [
            {
                label: '@startfpb',
                snippet: '@startfpb\n$0\n@endfpb',
                description: 'Start FPB diagram block',
                detail: 'Block delimiter'
            },
            {
                label: '@endfpb',
                snippet: '@endfpb',
                description: 'End FPB diagram block',
                detail: 'Block delimiter'
            },
            {
                label: '@boundary',
                snippet: '@boundary',
                description: 'Place state on the system limit boundary (half in, half out)',
                detail: 'Placement annotation'
            },
            {
                label: '@internal',
                snippet: '@internal',
                description: 'Place state fully inside the system limit',
                detail: 'Placement annotation'
            }
        ];

        return delimiters.map(delim => {
            const item = new vscode.CompletionItem(delim.label, vscode.CompletionItemKind.Keyword);
            item.insertText = new vscode.SnippetString(delim.snippet);
            item.documentation = new vscode.MarkdownString(delim.description);
            item.detail = delim.detail;
            item.sortText = `1_${delim.label}`; // Sort delimiters after keywords
            return item;
        });
    }

    /**
     * Get completion items for connection operators
     */
    private getConnectionOperatorCompletions(): vscode.CompletionItem[] {
        const operators = [
            {
                label: '-->',
                description: 'Flow connection - connects process operators with products, energy, or information',
                detail: 'Flow connection operator'
            },
            {
                label: '-.->',
                description: 'Alternative flow connection - represents alternative or conditional flows',
                detail: 'Alternative flow operator'
            },
            {
                label: '==>',
                description: 'Parallel flow connection - represents parallel processing paths',
                detail: 'Parallel flow operator'
            },
            {
                label: '<..>',
                description: 'Usage connection - connects technical resources or information to process operators',
                detail: 'Usage connection operator'
            }
        ];

        return operators.map(op => {
            const item = new vscode.CompletionItem(op.label, vscode.CompletionItemKind.Operator);
            item.insertText = `${op.label} `;
            item.documentation = new vscode.MarkdownString(op.description);
            item.detail = op.detail;
            item.sortText = `2_${op.label}`; // Sort operators last
            return item;
        });
    }
}

/**
 * Register the FPB completion provider
 */
export function registerCompletionProvider(context: vscode.ExtensionContext): void {
    const provider = new FpbCompletionProvider();
    const registration = vscode.languages.registerCompletionItemProvider(
        { scheme: 'file', language: 'fpb' },
        provider,
        ' ' // Trigger completion after space (for connection operators)
    );

    context.subscriptions.push(registration);
}
